version: '3.8'

services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - "9092:9092"

  db:
    image: postgres:15.2
    container_name: url_shortener
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: mercado
      POSTGRES_PASSWORD: libre
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    container_name: url-shortener
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning