spring.application.name=url-shortener

server.servlet.context-path=/url-shortener

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:url_shortener}
spring.datasource.username=${DATASOURCE_USER:mercado}
spring.datasource.password=${DATASOURCE_PASSWORD:libre}

logging.level.hibernate.SQL=DEBUG
logging.level.hibernate.type.descriptor.sql.BasicBinder=TRACE
